name: kubernetes
root: /local/flink-1.13.2/redpanda-state-backend-for-flink/kubernetes

windows:
  - kube_setup:
      layout: tiled
      panes:
      - experiments-shell:
        - cd ../experiments
      - kube-launch:
        - ./kube-teardown.sh; ./kube-startup.sh
      - directory-daemon:
        - cd ~/jiffy && directoryd
      - storage-daemon:
        - cd ~/jiffy && storaged
      - redpanda:
        - systemctl status redpanda
