apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      hostIPC: true
      containers:
      - name: taskmanager
        image: alxiang/redpanda-worker:4.0
        resources:
          requests:
            memory: "12Gi"
            cpu: "8"
          limits:
            memory: "12Gi"
            cpu: "8"
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
        - name: flink-input-data
          mountPath: /opt/flink/resources/
        securityContext:
          privileged: true
          runAsUser: 0  # refers to user _flink_ from official flink image, change if necessary
          capabilities:
            add: ["SYS_ADMIN"]
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  git clone https://github.com/alxiang/redpanda-state-backend-for-flink.git;
                  chown -R flink:flink redpanda-state-backend-for-flink;
                  cd redpanda-state-backend-for-flink && mvn clean package;
                  storaged --config /opt/flink/redpanda-state-backend-for-flink/cloudlab/jiffy.conf >/dev/null 2>&1 &
                  su - flink -c '/opt/flink/questdb-6.2.1-rt-linux-amd64/bin/questdb.sh start -d /opt/flink/.questdb' >/dev/null 2>&1 &
                  sleep 3 && watch -n 1 'chmod -R 777 /opt/flink/.questdb && chown -R flink:flink /opt/flink/.questdb' >/dev/null 2>&1 &

        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/bin/sh", "-c", "apt install -y dstat; git clone https://github.com/alxiang/redpanda-state-backend-for-flink.git && chown -R flink:flink redpanda-state-backend-for-flink && cd redpanda-state-backend-for-flink && mvn clean package; storaged --config /opt/flink/redpanda-state-backend-for-flink/cloudlab/jiffy.conf & su - flink -c '/opt/flink/questdb-6.2.1-rt-linux-amd64/bin/questdb.sh start -d /opt/flink/.questdb' & sleep 10" # watch -n 1 'chmod -R 777 /opt/flink/.questdb && chown -R flink:flink /opt/flink/.questdb' &
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: flink-input-data
        hostPath:
          path: /local/flink-1.13.2/redpanda-state-backend-for-flink/wikipedia/